version: "3.9"

services:
  mssql-db:
    container_name: mssql-database
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "STRONG_PASSWORD123"
      ACCEPT_EULA: "Y"
    volumes:
      - db-data:/var/lib/mysql/data
    networks:
      - brivent-internal
    ports:
      - "1433:1433"


volumes:
  db-data:
    driver: local

networks:
  brivent-internal:
    name: brivent-internal-network